### ISSUE TITLE
`GenServer` autocomplete options don't print their last character

### ISSUE THREAD

**Issue by smithjessk** [msaraiva/elixir_sense#16]
Migrated from [this issue on vscode-elixir](https://github.com/fr1zle/vscode-elixir/issues/106). 

---

The completions of the return values of `GenServer` statements are incomplete. For instance, one completion option for the following code stub is `{:reply, reply, new_state}`:

```elixir
defmodule TestVscodeAutocomplete do
  use GenServer

  def handle_call(request, from, state) do
    {}
  end
end
```

However, the last character of the autocomplete is always absent. This autocompletes to:

```elixir
defmodule TestVscodeAutocomplete do
  use GenServer

  def handle_call(request, from, state) do
    {:reply, reply, new_stat}
  end
end
```

This seems to be present for all of the options. For instance, `{:noreply, new_state, timeout | :hibernate}` is entered as `{:noreply, new_state, timeout | :hibernat}`. 

The problem also exists for `handle_info` and `handle_cast`.

Please let me know what other information you need from me. Thanks!

**Comment by msaraiva** [comment]
@smithjessk I've just tested this feature in Atom and ElixirLS. Both also use ElixirSense and both are working just fine. I think you should reopen the original issue. Maybe vscode-elixir is using an older version of ElixirSense.
