### ISSUE TITLE
No function clause matching on alias with newlines

### ISSUE THREAD

**Issue by evnu** [msaraiva/elixir_sense#17]
When trying to determine the location of an aliased module within `{}`, a newline seems to make elixir_sense encounter an error. Consider the following example (Tested with elixir-sense 1.0.1 in alchemist.vim (https://github.com/slashmili/alchemist.vim/commit/15e6439439997a02fddb65fd3db51c1eb62207c0)):

```sh
mix new bug
cd bug
mkdir lib/a
echo "defmodule A do\nalias A.{\nB\n}\nend" > lib/a.ex
echo "defmodule A.B do\nend\n" > lib/a/b.ex
mix compile
```

Within alchemist.vim, if I try to jump to `A.B` (thus, determine the location of definition), the following error occurs:

```
no function clause matching in anonymous fn/1 in ElixirSense.Core.MetadataBuilder.pre/2
```

Can you reproduce this?

**Comment by msaraiva** [comment]
It should work now using the latest version on master and using Elixir >= 1.6.0.
