### ISSUE TITLE
Publish to Hex

### ISSUE THREAD

**Issue by JakeBecker** [msaraiva/elixir_sense#2]
I'd like to use it as a dependency for an IDE plugin I'm working on.  👍

**Comment by msaraiva** [comment]
Sorry for taking so long to merge the code. I wasn't getting any notification from this project so I totally missed this one.

**Comment by JakeBecker** [comment]
No worries. I've just released https://github.com/JakeBecker/elixir-ls which uses Elixir Sense for a lot of the logic. I credited Elixir Sense in the readme and code comments. Currently has elixir_sense as a Github dependency but I can change it to hex once you've published it there. Thanks!
