### ISSUE TITLE
Proposal: add column number for definition

### ISSUE THREAD

**Issue by damnever** [msaraiva/elixir_sense#23]

**Comment by msaraiva** [comment]
@damnever working on it. See https://github.com/msaraiva/elixir_sense/issues/25#issuecomment-392991663

**Comment by msaraiva** [comment]
On master. Please pay attention that the provider now finds definitions of variables too. Therefore the API has changed. Also, in case of variables, the `file` field is always `nil`. For more info, see the [Location](https://github.com/msaraiva/elixir_sense/blob/4d63a5e347adab53a8f51680995d1e86391de536/lib/elixir_sense/providers/definition.ex#L14) type spec.
