### ISSUE TITLE
Replace deprecated Code.get_docs/2 with Code.fetch_docs/1

### ISSUE THREAD

**Issue by JakeBecker** [msaraiva/elixir_sense#30]
> deprecated: Code.get_docs/2 always returns nil as its outdated documentation is no longer stored on BEAM files. Use Code.fetch_docs/1 instead

If we want to maintain backwards compatibility with < 1.7, we can check `Version.match?(System.version(), ">= 1.7.0-dev")` at runtime.

I'll plan to tackle this in the next couple days unless you think you'll get to it first.

**Comment by michalmuskala** [comment]
I think it might be better to check with `function_exported?(Code, :fetch_docs, 1)` - no need to specify any exact version.

**Comment by msaraiva** [comment]
@JakeBecker Thanks for pointing that out. 
> I'll plan to tackle this in the next couple days unless you think you'll get to it first.

I'll only be able to take a look at this (and some other 1.7 related stuff) during the weekend. So feel free to give it a try.

**Comment by JakeBecker** [comment]
It's looking a bit more involved than I expected, there's a lot of tests failing in 1.7. If you think you'll get to it this weekend, I'd like to leave it to you. If not, I can take another look next week.

**Comment by msaraiva** [comment]
All fixed! Tests are green now. Only one warning related to the new `__STACKTRACE__` remains. 

@JakeBecker, Please pay attention to the following changes:
  - Find definition
    - New API as described [here](https://github.com/msaraiva/elixir_sense/issues/23)
    - Find definition of variables
  - Autocomplete
    - List fields of structs. Here an example:

![image](https://user-images.githubusercontent.com/457237/43438626-9addacec-9465-11e8-90eb-a95a0b4a14a4.png)

**Comment by JakeBecker** [comment]
Awesome! I already updated the code for find definition, I'll need to add the one for struct fields. (Great feature, btw.) Gonna try to get a release of ElixirLS with all the new stuff out by Friday.
